spring.application.name=tutor
spring.profiles.active=development
# web server tomcat config
server.servlet.context-path=/tutor
server.port=8080
server.tomcat.max-connections=300
server.tomcat.threads.max=30
server.tomcat.threads.min-spare=3
server.tomcat.accept-count=700
#server.tomcat.connection-timeout=30000
server.forward-headers-strategy=native
server.tomcat.max-http-form-post-size=20MB
server.tomcat.max-swallow-size=20MB
server.tomcat.remoteip.remote-ip-header=X-Real-IP
# db connection properties
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.encoding=UTF-8
#spring.datasource.url=jdbc:postgresql://db01.agrosmart.local:5432/farm_account?currentSchema=farm_account_test
#spring.jpa.properties.hibernate.default_schema=farm_account_test
#spring.datasource.username=farm_account_db_user
#spring.datasource.password=farmAccount#17022025UsEr!@
spring.datasource.url=jdbc:postgresql://localhost:5432/tutor?currentSchema=tutor
spring.jpa.properties.hibernate.default_schema=tutor
spring.datasource.username=astanserikov
spring.datasource.password=12345
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.connection-timeout=50000
#spring.datasource.hikari.idle-timeout=300000
#spring.datasource.hikari.max-lifetime=900000
spring.datasource.hikari.maximum-pool-size=7
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.connection-test-query=SELECT 1
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.id.new_generator_mappings=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
# jackson settings
spring.jackson.time-zone=Asia/Bishkek
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
# logging
logging.file.name=app.log
logging.level.org.springframework.web=error
logging.level.org.hibernate=ERROR
logging.level.com.zaxxer.hikari.HikariConfig=INFO
logging.level.com.zaxxer.hikari=INFO
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.directory=logs
logging.file.path=logs
# error response defaults
server.error.include-exception=false
server.error.include-stacktrace=never
server.error.path=/error
server.error.whitelabel.enabled=false
# default status rest message
message.default.welcome=Web service of the Farm Account
password.duration=90
# flyway
spring.flyway.enabled=true
maxRequestsPerIp=7
timeInSeconds=7000
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.deep-linking=true

spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.username=noreply@cs.kg
spring.mail.password=tknjsdftwgdrfmkn

spring.mail.protocol=smtp
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.debug=false

activation.link.test=http://localhost:8080/tutor/auth/activatecode?activationCode=%s
activation.link.prod=https://farm-lk.agrosmart.gov.kg/activatecode?activationCode=%s
reset.password.link.test=http://localhost:8080/tutor/auth/reset-password?token=%s
reset.password.link.prod=https://farm-lk.agrosmart.gov.kg/reset-password?token=%s


# files
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
file.base.url.prod=https://tutor/files/
file.base.url.test=http://localhost:8080/tutor/files/
test=AdM!n012345?
test.mode=true
