CREATE TABLE hb_cities
(
    id           BIGSERIAL PRIMARY KEY,
    alias        VARCHAR(255) UNIQUE,
    name_ru      VARCHAR(255),
    name_ky      VARCHAR(255),
    deleted      BOOLEAN            DEFAULT FALSE,
    edited_time  TIMESTAMP,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE advertisment
(
    id           BIGSERIAL PRIMARY KEY,
    description  VARCHAR(500),
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE advertisment_photo
(
    id              BIGSERIAL PRIMARY KEY,
    advertisment_id BIGINT                              NOT NULL,
    file_path       VARCHAR(500)                        NOT NULL,
    file_path_thumb VARCHAR(500),
    file_path_large VARCHAR(500),
    content_type    VARCHAR(100),
    created_time    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_advertisment_photo_advertisment FOREIGN KEY (advertisment_id)
        REFERENCES advertisment (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS hb_subjects
(
    id           BIGSERIAL PRIMARY KEY,
    alias        VARCHAR(255) UNIQUE,
    name_ru      VARCHAR(255),
    name_ky      VARCHAR(255),
    deleted      BOOLEAN            DEFAULT FALSE,
    edited_time  TIMESTAMP,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_roles
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias           VARCHAR(255)        NOT NULL UNIQUE,
    name_ru         VARCHAR(255)        NOT NULL,
    name_ky         VARCHAR(255)        NOT NULL,
    government_id   BIGINT,
    password_length INTEGER   DEFAULT 8 NOT NULL,
    deleted         BOOLEAN   DEFAULT FALSE,
    edited_time     TIMESTAMP           NULL,
    created_time    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_users
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_photo_id               BIGINT,
    can_comment                 BOOLEAN DEFAULT TRUE,
    name                        VARCHAR(255)                        NOT NULL,
    second_name                 VARCHAR(255)                        NOT NULL,
    email                       VARCHAR(255)                        NOT NULL,
    phone_number                VARCHAR(255),
    telegram                    VARCHAR(255),
    age                         integer,
    password                    VARCHAR(255)                        NOT NULL,
    last_password               VARCHAR(255),
    second_last_password        VARCHAR(255),
    third_last_password         VARCHAR(255),

    phone_number_verified       BOOLEAN   DEFAULT FALSE,
    email_verified              BOOLEAN   DEFAULT FALSE,

    gender                      VARCHAR(50),

    failed_login_attempts       INTEGER   DEFAULT 0,
    last_login                  TIMESTAMP,

    password_change_next_logon  BOOLEAN   DEFAULT TRUE,
    password_last_change_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    temporary_access_until_time TIMESTAMP,

    is_banned                   BOOLEAN   DEFAULT FALSE,
    deleted                     BOOLEAN   DEFAULT FALSE,

    edited_time                 TIMESTAMP,
    created_time                TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS user_photo
(
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT                              NOT NULL,
    file_path       VARCHAR(500)                        NOT NULL,
    file_path_thumb VARCHAR(500),
    file_path_large VARCHAR(500),
    content_type    VARCHAR(100),
    created_time    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_user_photo_user FOREIGN KEY (user_id) REFERENCES sys_users (id) ON DELETE CASCADE
);

ALTER TABLE sys_users
    ADD CONSTRAINT fk_user_photo FOREIGN KEY (user_photo_id)
        REFERENCES user_photo (id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS tutor_details
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT                     NOT NULL UNIQUE,
    rate     DOUBLE PRECISION DEFAULT 0 NOT NULL,
    price    DOUBLE PRECISION,
    city_id  BIGINT,
    about_me VARCHAR(1000),
    telegram VARCHAR(255),
    experience INTEGER,
    online   BOOLEAN,
    offline  BOOLEAN,
    at_tutor BOOLEAN,
    address  VARCHAR(255),

    CONSTRAINT fk_tutor_user FOREIGN KEY (user_id) REFERENCES sys_users (id) ON DELETE CASCADE,
    CONSTRAINT fk_tutor_city FOREIGN KEY (city_id) REFERENCES hb_cities (id)
);

CREATE TABLE IF NOT EXISTS tutor_reviews
(
    id           BIGSERIAL PRIMARY KEY,
    tutor_id     BIGINT                                      NOT NULL,
    author_id    BIGINT                                      NOT NULL,
    comment      VARCHAR(1000)                               NOT NULL,
    rating       INTEGER CHECK (rating >= 1 AND rating <= 5) NOT NULL,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP         NOT NULL,

    CONSTRAINT fk_review_tutor FOREIGN KEY (tutor_id) REFERENCES tutor_details (id) ON DELETE CASCADE,
    CONSTRAINT fk_review_author FOREIGN KEY (author_id) REFERENCES sys_users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tutor_education
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tutor_id        BIGINT NOT NULL,
    university      VARCHAR(255),
    graduation_year INTEGER,

    CONSTRAINT fk_tutor_education FOREIGN KEY (tutor_id) REFERENCES tutor_details (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS subject_experience
(
    id                     BIGSERIAL PRIMARY KEY,
    subject_id             BIGINT NOT NULL,
    tutor_id               BIGINT NOT NULL,
    experience_description VARCHAR(1000),

    CONSTRAINT fk_subject_experience_subject FOREIGN KEY (subject_id)
        REFERENCES hb_subjects (id) ON DELETE CASCADE,

    CONSTRAINT fk_subject_experience_tutor FOREIGN KEY (tutor_id)
        REFERENCES tutor_details (id) ON DELETE CASCADE
);
CREATE TABLE password_reset_token
(
    id          BIGSERIAL PRIMARY KEY,
    token       VARCHAR(255) NOT NULL,
    user_id     BIGINT       NOT NULL,
    expiry_date TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP + INTERVAL '1 hour',
    CONSTRAINT fk_password_reset_token_user FOREIGN KEY (user_id) REFERENCES sys_users (id) ON DELETE CASCADE
);

COMMENT ON TABLE password_reset_token IS 'Таблица для хранения токенов сброса пароля пользователей';
COMMENT ON COLUMN password_reset_token.id IS 'Уникальный идентификатор токена';
COMMENT ON COLUMN password_reset_token.token IS 'Генерируемый токен для сброса пароля';
COMMENT ON COLUMN password_reset_token.user_id IS 'ID пользователя, которому принадлежит токен';
COMMENT ON COLUMN password_reset_token.expiry_date IS 'Дата и время истечения срока действия токена';

CREATE TABLE sys_user_phone_numbers
(
    user_id      BIGINT       NOT NULL,
    phone_number VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (user_id, phone_number),
    CONSTRAINT fk_sys_user_phone_numbers_user_id FOREIGN KEY (user_id) REFERENCES sys_users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sys_user_roles
(
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    primary key (user_id, role_id),
    CONSTRAINT fk_sys_user_roles_user_id FOREIGN KEY (user_id) REFERENCES sys_users (id),
    CONSTRAINT fk_sys_user_roles_role_id FOREIGN KEY (role_id) REFERENCES sys_roles (id)
);


CREATE TABLE account_activation
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT                              NOT NULL REFERENCES sys_users (id) ON DELETE CASCADE,
    activation_code UUID                                NOT NULL UNIQUE,
    expires_at      TIMESTAMP                           NOT NULL,
    activated       BOOLEAN   DEFAULT FALSE,
    created_time    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    edited_time     TIMESTAMP                           NULL
);

COMMENT ON TABLE account_activation IS 'Таблица для хранения кодов активации аккаунта';
COMMENT ON COLUMN account_activation.id IS 'Уникальный идентификатор активации';
COMMENT ON COLUMN account_activation.user_id IS 'Идентификатор пользователя, которому принадлежит код активации';
COMMENT ON COLUMN account_activation.activation_code IS 'Уникальный код активации для пользователя';
COMMENT ON COLUMN account_activation.created_time IS 'Время создания записи с кодом активации';
COMMENT ON COLUMN account_activation.edited_time IS 'Время последнего редактирования';
COMMENT ON COLUMN account_activation.expires_at IS 'Время, когда код активации истекает';
COMMENT ON COLUMN account_activation.activated IS 'Флаг, указывающий на успешную активацию аккаунта';

CREATE TABLE IF NOT EXISTS action_logs
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT                              NOT NULL,
    object_type      VARCHAR(50)                         NOT NULL,
    http_method_type VARCHAR(10)                         NOT NULL,
    details          TEXT,
    remote_ip        VARCHAR(30),
    created_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_fa_action_logs_user FOREIGN KEY (user_id) REFERENCES sys_users (id)
);

COMMENT ON TABLE action_logs IS 'Журнал действий пользователей';
COMMENT ON COLUMN action_logs.id IS 'Уникальный идентификатор';
COMMENT ON COLUMN action_logs.user_id IS 'ID пользователя, совершившего действие';
COMMENT ON COLUMN action_logs.object_type IS 'Тип объекта (План, Задача, Заявка)';
COMMENT ON COLUMN action_logs.http_method_type IS 'Тип HTTP-запроса (GET, POST, PUT, DELETE)';
COMMENT ON COLUMN action_logs.details IS 'Дополнительные сведения о запросе';
COMMENT ON COLUMN action_logs.remote_ip IS 'IP-адрес пользователя';
COMMENT ON COLUMN action_logs.created_time IS 'Дата и время создания записи';

CREATE INDEX idx_fa_action_logs_user_id ON action_logs (user_id);
CREATE INDEX idx_fa_action_logs_object_type ON action_logs (object_type);
CREATE INDEX idx_fa_action_logs_http_method_type ON action_logs (http_method_type);
CREATE INDEX idx_fa_action_logs_created_time ON action_logs (created_time);

-- Сообщения об ошибках
CREATE TABLE IF NOT EXISTS error_message
(
    id          VARCHAR NOT NULL PRIMARY KEY,
    field       VARCHAR NOT NULL,
    message_ru  VARCHAR NOT NULL,
    message_kg  VARCHAR NOT NULL,
    message_eng VARCHAR NOT NULL
);

COMMENT ON TABLE error_message IS 'Сообщения об ошибках';
COMMENT ON COLUMN error_message.field IS 'Название поля, связанного с ошибкой';
COMMENT ON COLUMN error_message.message_ru IS 'Текст сообщения об ошибке на русском язык';
COMMENT ON COLUMN error_message.message_kg IS 'Текст сообщения об ошибке на кыргызском языке';
COMMENT ON COLUMN error_message.message_eng IS 'Текст сообщения об ошибке на английском языке';

-- Журнал Авторизаций
CREATE TABLE IF NOT EXISTS sys_logs_authorization
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    remote_ip    VARCHAR(30),
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sys_logs_authorization_user_id FOREIGN KEY (user_id) REFERENCES sys_users (id)
);

-- Журнал запросов
CREATE TABLE IF NOT EXISTS sys_logs_request
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_name   VARCHAR(255) NOT NULL,
    method_name  VARCHAR(255) NOT NULL,
    details      TEXT,
    status       VARCHAR(255) NOT NULL,
    user_id      BIGINT,
    remote_ip    VARCHAR(30),
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sys_logs_request_user_id FOREIGN KEY (user_id) REFERENCES sys_users (id)
);

CREATE INDEX idx_tutor_reviews_tutor_id ON tutor_reviews (tutor_id);


